---
- hosts: localhost
  become: true
  connection: local
  vars:
    enable_haproxy_admin_page: true
    haproxy_admin_password: 'admin'
    haproxy_admin_port: '9090'
    haproxy_admin_user: 'admin'
    haproxy_configs:
      - name: 'es_masters_9200'
        enabled: true
        mode: 'tcp'
        bind_port: '9200'
        service_name: 'es-masters' # Define name as back-end service name
        backend_service_port: '9200' # Define back-end service listening port
      - name: 'es_masters_9300'
        enabled: true
        mode: 'tcp'
        bind_port: '9300'
        service_name: 'es-masters' # Define name as back-end service name
        backend_service_port: '9300' # Define back-end service listening port
    haproxy_defaults:  #defines default configurations for default block
      - 'log global'
      - 'maxconn 40000'
      - 'mode tcp'
      - 'option dontlognull'
      - 'option redispatch'
      - 'option tcp-smart-accept'
      - 'option tcp-smart-connect'
      - 'option tcplog'
      - 'retries 3'
      - 'timeout client 50000'
      - 'timeout connect 50000'
      - 'timeout queue 5000'
      - 'timeout server 50000'
    haproxy_global:  #defines global settings for global block
      - 'chroot /var/lib/haproxy'
      - 'group haproxy'
      - 'maxconn 40000'
      - 'spread-checks 3'
      - 'stats timeout 30s'
      - 'user haproxy'
  tasks:
    - name: Configuring HAProxy
      template:
        src: "/haproxy.cfg.j2"
        dest: "/etc/haproxy/haproxy.cfg"
