---
- hosts: localhost
  connection: local
  become: true
  vars:
    - haproxy_repo: 'ppa:vbernat/haproxy-{{ haproxy_major_ver }}'
  tasks:
    - name: Update Apt-Cache
      apt:
        update_cache: yes

    - name: Installing apt-transport-https
      apt:
        name: "apt-transport-https"
        state: "present"

    - name: Installing ca-certificates
      apt:
        name: "ca-certificates"
        state: "latest"

    - name: Installing dumb-init
      apt:
        deb: "https://github.com/Yelp/dumb-init/releases/download/v1.0.2/dumb-init_1.0.2_amd64.deb"

    - name: Adding HAProxy PPA
      apt_repository:
        repo: "{{ haproxy_repo }}"
        state: "present"
        update_cache: yes

    - name: Installing HAProxy and Socat
      apt:
        name: "{{ item }}"
        state: "present"
        install_recommends: no
      with_items:
        - 'haproxy={{ haproxy_ver }}'
        - 'hatop'
        - 'socat'
